if (USE_AUTO_VCPKG)
	include(cmake/automate-vcpkg.cmake)

if ("${CMAKE_VS_PLATFORM_NAME}" STREQUAL "Win32")
    set(VCPKG_TRIPLET x86-windows-static)
    set(VCPKG_TARGET_TRIPLET x86-windows-static)
elseif ("${CMAKE_VS_PLATFORM_NAME}" STREQUAL "x64")
    set(VCPKG_TRIPLET x64-windows-static)
    set(VCPKG_TARGET_TRIPLET x64-windows-static)
elseif ("${CMAKE_VS_PLATFORM_NAME}" STREQUAL "arm64")
    set(VCPKG_TRIPLET arm64-windows-static)
    set(VCPKG_TARGET_TRIPLET arm64-windows-static)
endif()

	vcpkg_bootstrap()
	set(_lus_vcpkg_pkg_list zlib bzip2 sdl2 glew libzip nlohmann-json tinyxml2 spdlog)
	if(DEFINED LUS_VCPKG_EXTRA_PACKAGES)
		list(APPEND _lus_vcpkg_pkg_list ${LUS_VCPKG_EXTRA_PACKAGES})
	endif()
	vcpkg_install_packages(${_lus_vcpkg_pkg_list})
endif()
