if (USE_AUTO_VCPKG)
	include(cmake/automate-vcpkg.cmake)

	# Visual Studio generators set CMAKE_VS_PLATFORM_NAME; Ninja+MSVC (GHA
	# ilammy/msvc-dev-cmd) leaves it empty. Default to the static triplet so
	# we match libultraship's MultiThreaded CRT and BattleShip's curl search.
	if ("${CMAKE_VS_PLATFORM_NAME}" STREQUAL "Win32")
		set(VCPKG_TRIPLET x86-windows-static)
		set(VCPKG_TARGET_TRIPLET x86-windows-static)
	elseif ("${CMAKE_VS_PLATFORM_NAME}" STREQUAL "x64")
		set(VCPKG_TRIPLET x64-windows-static)
		set(VCPKG_TARGET_TRIPLET x64-windows-static)
	elseif ("${CMAKE_VS_PLATFORM_NAME}" STREQUAL "arm64")
		set(VCPKG_TRIPLET arm64-windows-static)
		set(VCPKG_TARGET_TRIPLET arm64-windows-static)
	elseif(NOT VCPKG_TRIPLET AND NOT VCPKG_TARGET_TRIPLET)
		if(CMAKE_SIZEOF_VOID_P EQUAL 8)
			set(VCPKG_TRIPLET x64-windows-static)
			set(VCPKG_TARGET_TRIPLET x64-windows-static)
		else()
			set(VCPKG_TRIPLET x86-windows-static)
			set(VCPKG_TARGET_TRIPLET x86-windows-static)
		endif()
		message(STATUS "CMAKE_VS_PLATFORM_NAME unset; using vcpkg triplet ${VCPKG_TARGET_TRIPLET}")
	endif()

	vcpkg_bootstrap()
	set(_lus_vcpkg_pkg_list zlib bzip2 sdl2 glew libzip nlohmann-json tinyxml2 spdlog)
	if(DEFINED LUS_VCPKG_EXTRA_PACKAGES)
		message(STATUS "LUS_VCPKG_EXTRA_PACKAGES: ${LUS_VCPKG_EXTRA_PACKAGES}")
		list(APPEND _lus_vcpkg_pkg_list ${LUS_VCPKG_EXTRA_PACKAGES})
	else()
		message(STATUS "LUS_VCPKG_EXTRA_PACKAGES: (unset)")
	endif()
	vcpkg_install_packages(${_lus_vcpkg_pkg_list})
endif()
