# Resolve Windows SDK um/x64 import libs (e.g. ksguid.lib for WASAPI) to full paths at
# configure time so Ninja link lines do not depend on LIB being present in every build
# subprocess. Newest SDK version dirs (e.g. 10.0.26100.0) may omit ksguid.lib; scan all.
# Only desktop um/x64 — never km/arm64 (also named ksguid.lib on GHA images).

function(_windows_sdk_um_glob_versions out_list)
    set(_roots "")
    if(EXISTS "C:/Program Files (x86)/Windows Kits/10/Lib")
        list(APPEND _roots "C:/Program Files (x86)/Windows Kits/10/Lib")
    endif()
    if(EXISTS "C:/Program Files/Windows Kits/10/Lib")
        list(APPEND _roots "C:/Program Files/Windows Kits/10/Lib")
    endif()
    set(_all_versions "")
    foreach(_root IN LISTS _roots)
        file(GLOB _versions "${_root}/*")
        if(_versions)
            list(APPEND _all_versions ${_versions})
        endif()
    endforeach()
    if(_all_versions)
        list(SORT _all_versions)
        list(REVERSE _all_versions)
    endif()
    set(${out_list} "${_all_versions}" PARENT_SCOPE)
endfunction()

function(_windows_sdk_um_is_um_x64_lib path)
    if(NOT path)
        set(_valid FALSE PARENT_SCOPE)
        return()
    endif()
    file(TO_CMAKE_PATH "${path}" _norm)
    if(_norm MATCHES "/um/x64/[^/]+\\.lib$")
        set(_valid TRUE PARENT_SCOPE)
    else()
        set(_valid FALSE PARENT_SCOPE)
    endif()
endfunction()

function(windows_sdk_um_find_lib lib_name out_var)
    set(_result "")
    if(NOT WIN32)
        set(${out_var} "" PARENT_SCOPE)
        return()
    endif()

    _windows_sdk_um_glob_versions(_wsu_versions)
    foreach(_ver IN LISTS _wsu_versions)
        set(_candidate "${_ver}/um/x64/${lib_name}.lib")
        if(EXISTS "${_candidate}")
            get_filename_component(_result "${_candidate}" ABSOLUTE)
            break()
        endif()
    endforeach()

    set(${out_var} "${_result}" PARENT_SCOPE)
endfunction()

function(windows_sdk_um_link_lib target visibility lib_name)
    if(NOT WIN32)
        target_link_libraries(${target} ${visibility} ${lib_name})
        return()
    endif()

    set(_ksguid_path "")
    if(DEFINED SSB64_KSGUID_LIB AND EXISTS "${SSB64_KSGUID_LIB}")
        _windows_sdk_um_is_um_x64_lib("${SSB64_KSGUID_LIB}" _ksguid_valid)
        if(_ksguid_valid)
            set(_ksguid_path "${SSB64_KSGUID_LIB}")
        else()
            message(WARNING "Ignoring SSB64_KSGUID_LIB (not um/x64): ${SSB64_KSGUID_LIB}")
        endif()
    endif()

    if(NOT _ksguid_path)
        windows_sdk_um_find_lib("${lib_name}" _ksguid_path)
    endif()

    if(_ksguid_path)
        message(STATUS "Windows SDK: linking ${lib_name} from ${_ksguid_path}")
        target_link_libraries(${target} ${visibility} "${_ksguid_path}")
    elseif(MINGW)
        target_link_libraries(${target} ${visibility} ${lib_name})
    else()
        message(FATAL_ERROR
            "Windows SDK: ${lib_name}.lib not found under "
            "Windows Kits/10/Lib/*/um/x64. "
            "Install the Windows 10 SDK desktop/um libraries on the build host.")
    endif()
endfunction()
